//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : photoworld
	/// Data Source    : photoworld
	/// Server Version : 3.50.4
	/// </summary>
	public partial class PhotoworldDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Photo> Photos { get { return this.GetTable<Photo>(); } }

		#endregion

		#region .ctor

		public PhotoworldDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PhotoworldDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PhotoworldDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public PhotoworldDB(DataOptions<PhotoworldDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="photos")]
	public partial class Photo
	{
		[Column("id"),   PrimaryKey, Identity, Nullable] public long?   Id   { get; set; } // INTEGER
		[Column("name"),                       Nullable] public string  Name { get; set; } // TEXT
		[Column("lng"),                        Nullable] public double? Lng  { get; set; } // REAL
		[Column("lat"),                        Nullable] public double? Lat  { get; set; } // REAL
	}

	public static partial class TableExtensions
	{
		public static Photo Find(this ITable<Photo> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
