//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Code
	/// Data Source    : Code
	/// Server Version : 3.50.4
	/// </summary>
	public partial class CodeDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<ActualCode>  ActualCodes  { get { return this.GetTable<ActualCode>(); } }
		public ITable<ProgramCode> ProgramCodes { get { return this.GetTable<ProgramCode>(); } }

		#endregion

		#region .ctor

		public CodeDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CodeDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CodeDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public CodeDB(DataOptions<CodeDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="actualCode")]
	public partial class ActualCode
	{
		[PrimaryKey, Identity, Nullable] public long?  Id         { get; set; } // INTEGER
		[Column,               Nullable] public long?  ProgramId  { get; set; } // INTEGER
		[Column,               Nullable] public long?  LineNumber { get; set; } // INTEGER
		[Column,               Nullable] public string Code       { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_actualCode_0 (main.ProgramCode)
		/// </summary>
		[Association(ThisKey=nameof(ProgramId), OtherKey=nameof(DataModels.ProgramCode.Id), CanBeNull=true)]
		public ProgramCode Program { get; set; }

		#endregion
	}

	[Table(Schema="main", Name="ProgramCode")]
	public partial class ProgramCode
	{
		[PrimaryKey, Identity, Nullable] public long?  Id   { get; set; } // INTEGER
		[Column,               Nullable] public string Name { get; set; } // TEXT
		[Column,               Nullable] public string Code { get; set; } // TEXT

		#region Associations

		/// <summary>
		/// FK_actualCode_0_BackReference (main.actualCode)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(DataModels.ActualCode.ProgramId), CanBeNull=true)]
		public IEnumerable<ActualCode> ActualCodes { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static ActualCode Find(this ITable<ActualCode> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProgramCode Find(this ITable<ProgramCode> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
